In [1]:
# import os
import re
# import math
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
# from sqlalchemy import create_engine
# import pymysql
# import requests
# from bs4 import BeautifulSoup
# from sklearn.linear_model import LinearRegression
# from statsmodels.tsa.ar_model import AR
# from statsmodels.tools.eval_measures import rmse
# from scipy import stats

In [2]:
pd.set_option('display.max_columns', 100)

In [ ]:
# Read both cocktails data sets and do cross check. Deside which to take as a basis.
# Align names.
# Add missing cocktails to the main dataset.
# Split ingredients from description, also include shape of glass, type of ice and way to mix as separate columns.
# Align measurements.
# Add labels: type of alcohol, tastes of other ingredients.

In [ ]:
### Collect cocktails raiting.
# Cross-check with dataset above. Align names. Add missing cocktails?

### Reading the first of cocktails datasets.

In [3]:
df_cocktails = pd.read_csv('.\\raw_data\\all_drinks.csv')
df_cocktails.drop('Unnamed: 0', axis=1, inplace=True)

In [4]:
df_cocktails.head()

,strDrink,dateModified,idDrink,strAlcoholic,strCategory,strDrinkThumb,strGlass,strIBA,strIngredient1,strIngredient10,strIngredient11,strIngredient12,strIngredient13,strIngredient14,strIngredient15,strIngredient2,strIngredient3,strIngredient4,strIngredient5,strIngredient6,strIngredient7,strIngredient8,strIngredient9,strInstructions,strMeasure1,strMeasure10,strMeasure11,strMeasure12,strMeasure13,strMeasure14,strMeasure15,strMeasure2,strMeasure3,strMeasure4,strMeasure5,strMeasure6,strMeasure7,strMeasure8,strMeasure9,strVideo
0,'57 Chevy with a White License Plate,2016-07-18 22:49:04,14029,Alcoholic,Cocktail,http://www.thecocktaildb.com/images/media/drin...,Highball glass,NaN,Creme de Cacao,NaN,NaN,NaN,NaN,NaN,NaN,Vodka,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1. Fill a rocks glass with ice 2.add white cre...,1 oz white,NaN,NaN,NaN,NaN,NaN,NaN,1 oz,,,,,,NaN,NaN,NaN
1,1-900-FUK-MEUP,2016-07-18 22:27:04,15395,Alcoholic,Shot,http://www.thecocktaildb.com/images/media/drin...,Old-fashioned glass,NaN,Absolut Kurant,NaN,NaN,NaN,NaN,NaN,NaN,Grand Marnier,Chambord raspberry liqueur,Midori melon liqueur,Malibu rum,Amaretto,Cranberry juice,Pineapple juice,NaN,Shake ingredients in a mixing tin filled with ...,1/2 oz,,,,,NaN,NaN,1/4 oz,1/4 oz,1/4 oz,1/4 oz,1/4 oz,1/2 oz,1/4 oz,,NaN
2,110 in the shade,2016-02-03 14:51:57,15423,Alcoholic,Beer,http://www.thecocktaildb.com/images/media/drin...,Beer Glass,NaN,Lager,NaN,NaN,NaN,NaN,NaN,NaN,Tequila,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Drop shooter in glass. Fill with beer,16 oz,NaN,NaN,NaN,NaN,NaN,NaN,1.5 oz,,,,,,NaN,NaN,NaN
3,151 Florida Bushwacker,2016-07-18 22:28:43,14588,Alcoholic,Milk / Float / Shake,http://www.thecocktaildb.com/images/media/drin...,Beer mug,NaN,Malibu rum,NaN,NaN,NaN,NaN,NaN,NaN,Light rum,151 proof rum,Dark Creme de Cacao,Cointreau,Milk,Coconut liqueur,Vanilla ice-cream,NaN,Combine all ingredients. Blend until smooth. G...,1/2 oz,,,,,NaN,NaN,1/2 oz,1/2 oz Bacardi,1 oz,1 oz,3 oz,1 oz,1 cup,,NaN
4,155 Belmont,2016-10-05 12:36:28,15346,Alcoholic,Cocktail,http://www.thecocktaildb.com/images/media/drin...,White wine glass,NaN,Dark rum,NaN,NaN,NaN,NaN,NaN,NaN,Light rum,Vodka,Orange juice,NaN,NaN,NaN,NaN,NaN,Blend with ice. Serve in a wine glass. Garnish...,1 shot,NaN,NaN,NaN,NaN,NaN,NaN,2 shots,1 shot,1 shot,,,,,,NaN

In [5]:
# Drop obviously excessive columns before detailed review of dataset.

df_cocktails.drop(['dateModified', 'idDrink', 'strDrinkThumb', 'strVideo'], axis=1, inplace=True)

In [6]:
df_cocktails.head()

,strDrink,strAlcoholic,strCategory,strGlass,strIBA,strIngredient1,strIngredient10,strIngredient11,strIngredient12,strIngredient13,strIngredient14,strIngredient15,strIngredient2,strIngredient3,strIngredient4,strIngredient5,strIngredient6,strIngredient7,strIngredient8,strIngredient9,strInstructions,strMeasure1,strMeasure10,strMeasure11,strMeasure12,strMeasure13,strMeasure14,strMeasure15,strMeasure2,strMeasure3,strMeasure4,strMeasure5,strMeasure6,strMeasure7,strMeasure8,strMeasure9
0,'57 Chevy with a White License Plate,Alcoholic,Cocktail,Highball glass,NaN,Creme de Cacao,NaN,NaN,NaN,NaN,NaN,NaN,Vodka,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1. Fill a rocks glass with ice 2.add white cre...,1 oz white,NaN,NaN,NaN,NaN,NaN,NaN,1 oz,,,,,,NaN,NaN
1,1-900-FUK-MEUP,Alcoholic,Shot,Old-fashioned glass,NaN,Absolut Kurant,NaN,NaN,NaN,NaN,NaN,NaN,Grand Marnier,Chambord raspberry liqueur,Midori melon liqueur,Malibu rum,Amaretto,Cranberry juice,Pineapple juice,NaN,Shake ingredients in a mixing tin filled with ...,1/2 oz,,,,,NaN,NaN,1/4 oz,1/4 oz,1/4 oz,1/4 oz,1/4 oz,1/2 oz,1/4 oz,
2,110 in the shade,Alcoholic,Beer,Beer Glass,NaN,Lager,NaN,NaN,NaN,NaN,NaN,NaN,Tequila,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Drop shooter in glass. Fill with beer,16 oz,NaN,NaN,NaN,NaN,NaN,NaN,1.5 oz,,,,,,NaN,NaN
3,151 Florida Bushwacker,Alcoholic,Milk / Float / Shake,Beer mug,NaN,Malibu rum,NaN,NaN,NaN,NaN,NaN,NaN,Light rum,151 proof rum,Dark Creme de Cacao,Cointreau,Milk,Coconut liqueur,Vanilla ice-cream,NaN,Combine all ingredients. Blend until smooth. G...,1/2 oz,,,,,NaN,NaN,1/2 oz,1/2 oz Bacardi,1 oz,1 oz,3 oz,1 oz,1 cup,
4,155 Belmont,Alcoholic,Cocktail,White wine glass,NaN,Dark rum,NaN,NaN,NaN,NaN,NaN,NaN,Light rum,Vodka,Orange juice,NaN,NaN,NaN,NaN,NaN,Blend with ice. Serve in a wine glass. Garnish...,1 shot,NaN,NaN,NaN,NaN,NaN,NaN,2 shots,1 shot,1 shot,,,,,

In [7]:
df_cocktails.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 546 entries, 0 to 545
Data columns (total 36 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   strDrink         546 non-null    object
 1   strAlcoholic     545 non-null    object
 2   strCategory      546 non-null    object
 3   strGlass         546 non-null    object
 4   strIBA           71 non-null     object
 5   strIngredient1   546 non-null    object
 6   strIngredient10  3 non-null      object
 7   strIngredient11  3 non-null      object
 8   strIngredient12  1 non-null      object
 9   strIngredient13  0 non-null      float64
 10  strIngredient14  0 non-null      float64
 11  strIngredient15  0 non-null      float64
 12  strIngredient2   546 non-null    object
 13  strIngredient3   461 non-null    object
 14  strIngredient4   294 non-null    object
 15  strIngredient5   166 non-null    object
 16  strIngredient6   78 non-null     object
 17  strIngredient7   25 non-null     object
 18  strIngredient8   15 non-null     object
 19  strIngredient9   6 non-null      object
 20  strInstructions  545 non-null    object
 21  strMeasure1      546 non-null    object
 22  strMeasure10     144 non-null    object
 23  strMeasure11     66 non-null     object
 24  strMeasure12     20 non-null     object
 25  strMeasure13     12 non-null     object
 26  strMeasure14     4 non-null      object
 27  strMeasure15     3 non-null      object
 28  strMeasure2      543 non-null    object
 29  strMeasure3      539 non-null    object
 30  strMeasure4      527 non-null    object
 31  strMeasure5      520 non-null    object
 32  strMeasure6      523 non-null    object
 33  strMeasure7      522 non-null    object
 34  strMeasure8      414 non-null    object
 35  strMeasure9      257 non-null    object
dtypes: float64(3), object(33)
memory usage: 153.7+ KB

In [8]:
df_cocktails['strIBA'].unique()

array([nan, 'Unforgettables', 'New Era Drinks', 'Contemporary Classics'],
      dtype=object)

In [9]:
# One more unneccessary column.

df_cocktails.drop('strIBA', axis=1, inplace=True)

In [10]:
# Check and fill in missing value in 'Alcoholic' category. It's not possible to remove non-alcoholic rows having Nan in the column.

df_cocktails.loc[df_cocktails['strAlcoholic'].isnull()]

,strDrink,strAlcoholic,strCategory,strGlass,strIngredient1,strIngredient10,strIngredient11,strIngredient12,strIngredient13,strIngredient14,strIngredient15,strIngredient2,strIngredient3,strIngredient4,strIngredient5,strIngredient6,strIngredient7,strIngredient8,strIngredient9,strInstructions,strMeasure1,strMeasure10,strMeasure11,strMeasure12,strMeasure13,strMeasure14,strMeasure15,strMeasure2,strMeasure3,strMeasure4,strMeasure5,strMeasure6,strMeasure7,strMeasure8,strMeasure9
190,Cherry Electric Lemonade,NaN,Cocktail,Pint glass,Gin,NaN,NaN,NaN,NaN,NaN,NaN,Tequila,Vodka,White rum,Triple Sec,Cherry Grenadine,Sweet and sour,Club soda,NaN,Now stir vigorously and then pour over a large...,1 oz,NaN,NaN,NaN,NaN,NaN,NaN,1 oz,1 oz,1 oz,1 oz,1 oz,1 oz,3 oz,NaN

In [11]:
df_cocktails['strAlcoholic'].fillna('Alcoholic', inplace=True)

In [12]:
# Check how many of non-alcoholic cocktails there are in dataset and drop these rows.

df_cocktails['strAlcoholic'].value_counts()

Alcoholic           479
Non alcoholic        57
Optional alcohol      9
Non Alcoholic         1
Name: strAlcoholic, dtype: int64

In [13]:
non_alc = df_cocktails.loc[df_cocktails['strAlcoholic'].str.contains('Non')].index
df_cocktails.drop(non_alc, axis=0, inplace=True)
df_cocktails.drop('strAlcoholic', axis=1, inplace=True)

In [14]:
# Check and fill in missing instruction.

df_cocktails.loc[df_cocktails['strInstructions'].isna()]

,strDrink,strCategory,strGlass,strIngredient1,strIngredient10,strIngredient11,strIngredient12,strIngredient13,strIngredient14,strIngredient15,strIngredient2,strIngredient3,strIngredient4,strIngredient5,strIngredient6,strIngredient7,strIngredient8,strIngredient9,strInstructions,strMeasure1,strMeasure10,strMeasure11,strMeasure12,strMeasure13,strMeasure14,strMeasure15,strMeasure2,strMeasure3,strMeasure4,strMeasure5,strMeasure6,strMeasure7,strMeasure8,strMeasure9
9,410 Gone,Ordinary Drink,Collins Glass,Peach Vodka,NaN,NaN,NaN,NaN,NaN,NaN,Coca-Cola,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2-3 oz,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [15]:
df_cocktails['strInstructions'].fillna('Pour 2oz Vodka into a low ball glass, top up with Coke.', inplace=True)

In [16]:
# Check 'Ingredient' columns where there are no values in 'Ingredients' but there are some values in 'Measures'.

df_cocktails.loc[df_cocktails['strMeasure13'].notnull()]

,strDrink,strCategory,strGlass,strIngredient1,strIngredient10,strIngredient11,strIngredient12,strIngredient13,strIngredient14,strIngredient15,strIngredient2,strIngredient3,strIngredient4,strIngredient5,strIngredient6,strIngredient7,strIngredient8,strIngredient9,strInstructions,strMeasure1,strMeasure10,strMeasure11,strMeasure12,strMeasure13,strMeasure14,strMeasure15,strMeasure2,strMeasure3,strMeasure4,strMeasure5,strMeasure6,strMeasure7,strMeasure8,strMeasure9
1,1-900-FUK-MEUP,Shot,Old-fashioned glass,Absolut Kurant,NaN,NaN,NaN,NaN,NaN,NaN,Grand Marnier,Chambord raspberry liqueur,Midori melon liqueur,Malibu rum,Amaretto,Cranberry juice,Pineapple juice,NaN,Shake ingredients in a mixing tin filled with ...,1/2 oz,,,,,NaN,NaN,1/4 oz,1/4 oz,1/4 oz,1/4 oz,1/4 oz,1/2 oz,1/4 oz,
3,151 Florida Bushwacker,Milk / Float / Shake,Beer mug,Malibu rum,NaN,NaN,NaN,NaN,NaN,NaN,Light rum,151 proof rum,Dark Creme de Cacao,Cointreau,Milk,Coconut liqueur,Vanilla ice-cream,NaN,Combine all ingredients. Blend until smooth. G...,1/2 oz,,,,,NaN,NaN,1/2 oz,1/2 oz Bacardi,1 oz,1 oz,3 oz,1 oz,1 cup,
8,3-Mile Long Island Iced Tea,Ordinary Drink,Collins Glass,Gin,NaN,NaN,NaN,NaN,NaN,NaN,Light rum,Tequila,Triple sec,Vodka,Coca-Cola,Sweet and sour,Bitters,Lemon,Fill 14oz glass with ice and alcohol. Fill 2/3...,1/2 oz,,,,,NaN,NaN,1/2 oz,1/2 oz,1/2 oz,1/2 oz,\n,1-2 dash,1 wedge,
74,Amaretto Liqueur,Homemade Liqueur,Collins Glass,Sugar,Food coloring,Glycerine,NaN,NaN,NaN,NaN,Water,Apricot,Almond flavoring,Grain alcohol,Water,Brandy,Food coloring,Food coloring,Combine sugar and 3/4 cup water in a small sau...,1 cup,2 drops blue,1/2 tsp,,,,,3/4 cup,2,1 tblsp,1/2 cup pure,1/2 cup,1 cup,3 drops yellow,6 drops red
88,Angelica Liqueur,Homemade Liqueur,Collins Glass,Angelica root,Water,Food coloring,Food coloring,NaN,NaN,NaN,Almond,Allspice,Cinnamon,Anise,Coriander,Marjoram leaves,Vodka,Sugar,"Combine all herbs, nuts and spices with vodka ...",3 tblsp chopped,1/4 cup,1 drop yellow,1 drop green,,,,1 tblsp chopped,1 cracked,1 one-inch,3-6 crushed,1/8 tsp powdered,1 tblsp fresh chopped,1.5 cup,1/2 cup granulated
91,Apple Cider Punch #1,Punch / Party Drink,Collins Glass,Apple cider,NaN,NaN,NaN,NaN,NaN,NaN,Brown sugar,Lemonade,Orange juice,Cloves,Allspice,Nutmeg,Cinnamon,NaN,"If you use the whole all spice and cloves, tie...",4 qt,,,,,NaN,NaN,1 cup,6 oz frozen,6 oz frozen,6 whole,6 whole,1 tsp ground,3 sticks,
106,Arizona Twister,Cocktail,Hurricane glass,Vodka,NaN,NaN,NaN,NaN,NaN,NaN,Malibu rum,Gold tequila,Orange juice,Pineapple juice,Cream of coconut,Grenadine,Ice,Pineapple,"Just mix in the shots of rum, vodka, and tequi...",1 shot,,,,,,NaN,1 shot,1 shot,1 splash,1 splash,1 splash,1 dash,crushed,1 wedge
110,Artillery Punch,Punch / Party Drink,Punch bowl,Tea,NaN,NaN,NaN,NaN,NaN,NaN,Rye whiskey,Red wine,Rum,Brandy,Benedictine,Orange juice,Lemon juice,NaN,Combine all the ingredients in a large punch b...,1 quart black,,,,,NaN,NaN,1 quart,1 fifth,1 pint Jamaican,1/2 pint,1 1/2 oz,1 pint,1/2 pint,
197,Chocolate Monkey,Milk / Float / Shake,Parfait glass,Banana liqueur,NaN,NaN,NaN,NaN,NaN,NaN,Creme de Cacao,Chocolate ice-cream,Chocolate syrup,Chocolate milk,Whipped cream,Cherry,Banana,NaN,"blend liqeuors with ice-cream, milk and syrup....",1 shot,,,,,NaN,NaN,2 shots,2 scoops,1 oz,4 oz,1,1,1 piece,
231,Egg Nog #4,Punch / Party Drink,Punch bowl,Egg yolk,Sugar,Nutmeg,NaN,NaN,NaN,NaN,Sugar,Milk,Light rum,Bourbon,Vanilla extract,Salt,Whipping cream,Egg white,In a small mixer bowl beat egg yolks till blen...,6,1/4 cup,Ground,,,,,1/4 cup,2 cups,1/2 cup,1/2 cup,1 tsp,1/4 tsp,1 cup,6
425,Radioactive Long Island Iced Tea,Ordinary Drink,Collins Glass,Rum,NaN,NaN,NaN,NaN,NaN,NaN,Vodka,Tequila,Gin,Triple sec,Chambord raspberry liqueur,Midori melon liqueur,Malibu rum,NaN,Pour all ingredients over ice in a very tall g...,1 oz,,,,,NaN,NaN,1 oz,1 oz,1 oz,1 oz,1 oz,1 oz,1 oz,

In [17]:
# Replare blanks with Nan for concistancy.

df_cocktails = df_cocktails.replace(r'^\s+$', np.nan, regex=True)
df_cocktails.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 488 entries, 0 to 545
Data columns (total 34 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   strDrink         488 non-null    object
 1   strCategory      488 non-null    object
 2   strGlass         488 non-null    object
 3   strIngredient1   488 non-null    object
 4   strIngredient10  3 non-null      object
 5   strIngredient11  3 non-null      object
 6   strIngredient12  1 non-null      object
 7   strIngredient13  0 non-null      float64
 8   strIngredient14  0 non-null      float64
 9   strIngredient15  0 non-null      float64
 10  strIngredient2   488 non-null    object
 11  strIngredient3   412 non-null    object
 12  strIngredient4   259 non-null    object
 13  strIngredient5   147 non-null    object
 14  strIngredient6   71 non-null     object
 15  strIngredient7   22 non-null     object
 16  strIngredient8   14 non-null     object
 17  strIngredient9   5 non-null      object
 18  strInstructions  488 non-null    object
 19  strMeasure1      480 non-null    object
 20  strMeasure10     3 non-null      object
 21  strMeasure11     3 non-null      object
 22  strMeasure12     1 non-null      object
 23  strMeasure13     0 non-null      float64
 24  strMeasure14     0 non-null      float64
 25  strMeasure15     0 non-null      float64
 26  strMeasure2      470 non-null    object
 27  strMeasure3      385 non-null    object
 28  strMeasure4      227 non-null    object
 29  strMeasure5      121 non-null    object
 30  strMeasure6      53 non-null     object
 31  strMeasure7      18 non-null     object
 32  strMeasure8      12 non-null     object
 33  strMeasure9      4 non-null      object
dtypes: float64(6), object(28)
memory usage: 133.4+ KB

In [18]:
# Columns related to 13, 14 & 15 ingredient can be dropped.

df_cocktails.drop(['strIngredient13', 'strIngredient14', 'strIngredient15', 'strMeasure13', 'strMeasure14', 'strMeasure15'],
                 axis=1, inplace=True)
df_cocktails.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 488 entries, 0 to 545
Data columns (total 28 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   strDrink         488 non-null    object
 1   strCategory      488 non-null    object
 2   strGlass         488 non-null    object
 3   strIngredient1   488 non-null    object
 4   strIngredient10  3 non-null      object
 5   strIngredient11  3 non-null      object
 6   strIngredient12  1 non-null      object
 7   strIngredient2   488 non-null    object
 8   strIngredient3   412 non-null    object
 9   strIngredient4   259 non-null    object
 10  strIngredient5   147 non-null    object
 11  strIngredient6   71 non-null     object
 12  strIngredient7   22 non-null     object
 13  strIngredient8   14 non-null     object
 14  strIngredient9   5 non-null      object
 15  strInstructions  488 non-null    object
 16  strMeasure1      480 non-null    object
 17  strMeasure10     3 non-null      object
 18  strMeasure11     3 non-null      object
 19  strMeasure12     1 non-null      object
 20  strMeasure2      470 non-null    object
 21  strMeasure3      385 non-null    object
 22  strMeasure4      227 non-null    object
 23  strMeasure5      121 non-null    object
 24  strMeasure6      53 non-null     object
 25  strMeasure7      18 non-null     object
 26  strMeasure8      12 non-null     object
 27  strMeasure9      4 non-null      object
dtypes: object(28)
memory usage: 110.6+ KB

In [19]:
# Consolidate all ingredients and all measures in two columns.

df_cons = pd.DataFrame(columns = ['strDrink', 'strCategory', 'strGlass', 'strIngredients','strInstructions', 'strMeasures'])
for i in range(1,13):
    temp = df_cocktails[['strDrink', 'strCategory', 'strGlass', 'strIngredient'+str(i),'strInstructions', 'strMeasure'+str(i)]]
    temp.columns = ['strDrink', 'strCategory', 'strGlass', 'strIngredients','strInstructions', 'strMeasures']
    df_cons = df_cons.append(temp)

# Reset index so it can be used for reference in the future
df_cons.reset_index(inplace=True)
df_cons.drop('index', axis=1, inplace=True)

# Remove lines with no ingredients.
df_cons.drop(df_cons.loc[df_cons['strIngredients'].isnull()].index, axis=0, inplace=True)

# Reset index again so it can be used for reference in the future.
df_cons.reset_index(inplace=True)
df_cons.drop('index', axis=1, inplace=True)

df_cons.shape

(1913, 6)

In [132]:
# Align capitalisation of all ingredients & measures.

df_cons['strIngredients'] = df_cons['strIngredients'].str.title()
df_cons['strMeasures'] = df_cons['strMeasures'].str.lower()

In [21]:
# Replace Nan back with '' to be able to use all functionality of pandas.

df_cons.fillna('', inplace=True)

### Data is now considered to be generally clean. Next step - unify mesurements.

In [22]:
# Remove whitespaces in the beginning and in the end of the string.

df_cons['strMeasures'] = df_cons['strMeasures'].apply(lambda x: str(x).strip())

In [133]:
df_cons['strMeasures'].unique()

array(['1 oz white', '1/2 oz', '16 oz', '1 shot', '1/2 shot bacardi',
       '1/3 oz', '2-3 oz', '2 1/2 oz', '', '2 oz dry', '1/3 part', '2 oz',
       '1 oz', '1 jigger', '1 1/2 oz', '1 3/4 shot', '1/3',
       '1 oz bacardi', '2 shots', '2/3 part', '3/4 oz', '2/3', '1 part',
       '1/2', '1 1/2 shot', '2 cl', '1 cl', '2 dashes', '2 scoops',
       '1/2 jigger', '6 oz hot', '4 qt', '3 oz', '3 parts', '1 qt',
       '5 oz blue', 'chilled', '30 ml', '1 1/2 tsp', '1 quart black',
       '2 cl smirnoff', '5 oz', '4 cl', '4.5 cl', '1 can', '1/3 shot',
       '1 3/4 oz bacardi', '6 oz', '8 cubes', '2 pint',
       '1 part bass pale', 'cubes', '3 cups', '1 tsp superfine',
       '1 fifth', '30 ml white', '1/4', '1', '2 tsp', '2', '1 bottle',
       '1 1/4 oz', '1/2 shot', '3 dashes', '1-2 shot', '0.75 oz', '5 cl',
       '6 cl', '1/2 pint', '70ml/2fl oz', '2 part', '6', '1/2 cup',
       '1/4 glass', '2 1/2 shots', '5 parts', '25 ml', '1 l', '2 parts',
       '1 1/2 cl', '1/2 pint hard', '12 parts', '5 shots', '1 long strip',
       '4-5', '2/3 oz', '1/6 glass', '2 cups', '2 jiggers', '2 oz light',
       '1/2 oz grape', '3/4 bottle', '1 2/3 oz', '5 oz bacardi',
       '1/2 handful', '2/5', '750 ml', '1.5 oz', '4 oz', '1/2 oz white',
       '12 oz', '7 parts', '1 tblsp', '1 1/2', '2 oz light or dark',
       'mikey bottle', '2.5 cl', '1 1/2 l', '1 tsp', '1 oz jamaican',
       '2 oz cream', '1 1/2 oz cream', '1 shot bacardi', '46 oz chilled',
       '1 cup', '8 oz', '2 measures', 'full glass', '4cl',
       '2 oz white or', '3 cl', '4 shots', '1 1/4 oz stoli', '1/4 oz',
       '1 splash', 'juice of 1/2', '1 dash', '1/2 can', '1 1/2 oz dry',
       '3 shots', '1 oz red', '4 fifth', '1 oz green ginger',
       '12 oz lemon', '1 quart', '1.5 cl',
       '1 bottle boone strawberry hill', '1 slice',
       '1 fifth smirnoff red label', '1 whole', '2 tblsp', 'juice of 1',
       '1/4 tsp', '1 piece', 'squeeze', '0.25 oz', '10 cl', '1 tbsp',
       '1/4 cup', '3 tblsp', '3/4 glass', '2 tsp superfine', '4 chunks',
       '15 ml', '125 ml', '3/4 oz white', '8 cl', '8 parts', 'very sweet',
       '3/4 shot', 'strong cold', '1 shot jamaican',
       '1/6 glass strong black', '3 packages', '1/2 tsp tropical',
       'turkish apple', '2 1/2 oz blended', 'frozen', '0.5 oz', '4 parts',
       '1750 ml', '1/2 part', '1/2 tsp', '9 parts', '1/3 oz cream',
       'add 250 ml', 'large bottle', '1/2 tsp superfine', '4 dashes',
       '3 cans', '1/2 pint sweet or dry', '8-10 oz cold', '28 oz',
       'about 8 drops', '3cl', 'add 10 oz', '16 cl', '1/2 oz bacardi',
       'fill with', '1 twist of', '1/4 shot', 'juice of 1/4',
       'top up with', '1/4 cl', 'twist of', '6 oz frozen', '45 ml',
       '6 parts', '7 oz', '1/2 gal', '2 wedges', '1/2 glass', '1 1/4 tsp',
       '2 l', '5 ml', '1/2 oz muscatel', '2 fresh leaves', '2 tbsp',
       '13 oz skimmed', '1 cube', '10 ml', '60 gr', 'to taste',
       '1/2 glass cold', '7 cl', '(if needed)', 'juice of 1 wedge',
       'wedge', 'dash', '3/4 oz double', '1/8 l jamaican', '1/5', '12',
       '2 oz sweetened', '12 oz frozen', '1-2 tblsp', '1/2 oz cream',
       '2 splashes', '355 ml frozen', '3-4 oz', '1 large', '1 1/2 cup',
       'a little bit of', 'splash', 'by taste', '2 spoons', '0.75 cl',
       '3 oz unsweetened', '2cl', '4 oz grape', '5', '1/8 shot',
       'top it up with', 'add', 'fill to top', '10 tsp', '4 cl hot',
       'add splash', 'add 1/2 cup', '4 l', 'lots', '1/2 glass crushed',
       '1 pint jamaican', '1 1/2 part', 'about 1 bottle',
       '1 gal tropical berry', 'coarse', 'for topping', '1/2 slice',
       'crushed', '1 wedge', 'float bacardi', '3/4 cup skimmed',
       '4 oz chilled', '4', '3 chunks', '2 1/2 parts', '10-12 oz',
       '2 pinches', 'bacardi', '1 dl schweppes', '2 or 3', '2-4', '1/8 l',
       '(claret)', '1 package', '1 cup crushed', '1 gal',
       '1/8 tsp grated', '3 tblsp fresh', '3', 'or lime', '1/2 fresh',
       '6 whole', 'top up', 'to fill', '2-3 drops', '4 tablespoons',
       '1 small bottle', 'garnish', 'around rim put 1 pinch',
       '2 oz hazlenut', '8 drops', 'over', '1 pint', 'pinch',
       '3-4 oz plain', '1 pinch', '1-2 dash', '1-3 pint', '1 tsp ground',
       '15', '2 sprigs', 'fill to top with', '3 sticks', 'ground'],
      dtype=object)

In [24]:
# Split of measure column in values and measure names.

df_cons = df_cons.join(df_cons['strMeasures'].str.rsplit(n=1, expand=True).rename(columns={0: 'Value', 1: 'MeasureName'}))

In [25]:
df_cons['MeasureName'].unique()

array(['white', 'oz', 'shot', 'Bacardi', None, 'dry', 'part', 'jigger',
       'shots', 'bottle', 'cl', 'dashes', 'cup', 'scoops', 'hot',
       'chopped', 'qt', 'parts', 'blue', 'ml', 'tsp', 'black', 'Smirnoff',
       'can', 'cubes', 'pint', 'pale', 'cups', 'superfine', 'fifth',
       'large', 'instant', 'glass', 'L', 'hard', 'strip', 'jiggers',
       'light', 'Grape', 'handful', 'cL', 'tblsp', '1/2', 'dark',
       'Jamaican', 'cream', 'chilled', 'bottles', 'measures', 'or',
       'Stoli', 'splash', 'Shot', 'dash', 'gr', 'red', 'Ginger', 'lemon',
       'quart', 'Hill', 'slice', 'label', 'whole', '1', 'piece', 'tbsp',
       'chunks', 'sweet', 'cold', 'packages', 'Tropical', 'apple',
       'Blended', 'mild', 'cans', 'drops', 'with', 'of', '1/4', 'pure',
       'cracked', 'frozen', 'gal', 'wedges', 'Muscatel', 'leaves',
       'skimmed', 'cube', 'taste', 'sweetened', 'needed)', 'wedge',
       'double', 'splashes', 'spoons', 'unsweetened', 'top', 'one-inch',
       'crushed', 'Berry', 'topping', 'Chilled', 'pinches', 'Schweppes',
       '3', 'package', 'grated', 'fresh', 'lime', 'Fresh', 'up', 'fill',
       'tablespoons', 'green', 'Dashes', 'boiling', 'pinch', 'Hazlenut',
       'strips', 'powdered', 'plain', 'ground', 'sprigs', 'yellow',
       'sticks', 'granulated'], dtype=object)

In [26]:
df_cons.sort_values('MeasureName')

,strDrink,strCategory,strGlass,strIngredients,strInstructions,strMeasures,Value,MeasureName
658,California Lemonade,Ordinary Drink,Collins glass,Lemon,Shake all ingredients (except carbonated water...,Juice of 1,Juice of,1
1023,After Dinner Cocktail,Ordinary Drink,Cocktail glass,Lime,Shake all ingredients (except lime wedge) with...,Juice of 1,Juice of,1
823,Mojito,Cocktail,Highball glass,Lime,Muddle mint leaves with sugar and lime juice. ...,Juice of 1,Juice of,1
1122,California Lemonade,Ordinary Drink,Collins glass,Lime,Shake all ingredients (except carbonated water...,Juice of 1,Juice of,1
1185,Gin Rickey,Cocktail,Highball glass,Lemon,Half-fill a tall glass with ice. Mix the gin a...,Juice of 1/2,Juice of,1/2
...,...,...,...,...,...,...,...,...
1894,Arizona Twister,Cocktail,Hurricane glass,Ice,"Just mix in the shots of rum, vodka, and tequi...",crushed,crushed,None
1900,Sweet Sangria,Punch / Party Drink,Pitcher,Fresca,Dissolve the sugar in hot water and cool. Peel...,,None,None
1901,3-Mile Long Island Iced Tea,Ordinary Drink,Collins Glass,Lemon,Fill 14oz glass with ice and alcohol. Fill 2/3...,,None,None
1905,Egg Nog #4,Punch / Party Drink,Punch bowl,Egg White,In a small mixer bowl beat egg yolks till blen...,6,6,None
1911,Egg Nog #4,Punch / Party Drink,Punch bowl,Nutmeg,In a small mixer bowl beat egg yolks till blen...,Ground,Ground,None

In [27]:
# Set up of new columns to be filled in and used going forward.

df_cons['Value_ml'] = np.nan
df_cons['Garnish_amount'] = np.nan
df_cons['Garnish_type'] = np.nan

**Code below is pretty unstructured because original 'Measures' data is very messy and unstructured. So whatever catches an eye first is corrected first.**

\* Note: all individual adjustments are either verified with instructions included in this dataset or with most common recipe available in the Internet.

In [28]:
# Function to print all ingredients with measures and instructions for given cocktail. Comes handy for spot check.

def recipe(name):
    ingredient = []
    measure = []
    for i in range (1, 13):
        ingredient.append(df_cocktails.loc[df_cocktails['strDrink'] == name]['strIngredient'+str(i)].values[0])
        measure.append(df_cocktails.loc[df_cocktails['strDrink'] == name]['strMeasure'+str(i)].values[0])
    df_recipe = pd.DataFrame({'Ingredient': ingredient, 'Measure': measure})
    
    print(df_cocktails.loc[df_cocktails['strDrink'] == name]['strInstructions'].values[0])
    return df_recipe

## Lemons.

In [29]:
df_cons.loc[df_cons['strIngredients'] == 'Lemon']

,strDrink,strCategory,strGlass,strIngredients,strInstructions,strMeasures,Value,MeasureName,Value_ml,Garnish_amount,Garnish_type
509,A True Amaretto Sour,Cocktail,Old-fashioned glass,Lemon,Rub the rim of an old fashioned glass with lem...,Juice of 1/2,Juice of,1/2,NaN,NaN,NaN
636,Boston Sour,Ordinary Drink,Whiskey sour glass,Lemon,"Shake juice of lemon, powdered sugar, blended ...",Juice of 1/2,Juice of,1/2,NaN,NaN,NaN
647,Brandy Sour,Ordinary Drink,Whiskey sour glass,Lemon,"Shake brandy, juice of lemon, and powdered sug...",Juice of 1/2,Juice of,1/2,NaN,NaN,NaN
658,California Lemonade,Ordinary Drink,Collins glass,Lemon,Shake all ingredients (except carbonated water...,Juice of 1,Juice of,1,NaN,NaN,NaN
731,Gin Fizz,Ordinary Drink,Highball glass,Lemon,"Shake all ingredients with ice cubes, except s...",Juice of 1/2,Juice of,1/2,NaN,NaN,NaN
733,Gin Sling,Ordinary Drink,Old-fashioned glass,Lemon,Dissolve powdered sugar in mixture of water an...,Juice of 1/2,Juice of,1/2,NaN,NaN,NaN
777,Japanese Fizz,Ordinary Drink,Highball glass,Lemon,Shake all ingredients (except carbonated water...,Juice of 1/2,Juice of,1/2,NaN,NaN,NaN
835,New York Sour,Ordinary Drink,Whiskey sour glass,Lemon,"Shake blended whiskey, juice of lemon, and pow...",Juice of 1/2,Juice of,1/2,NaN,NaN,NaN
875,Royal Gin Fizz,Ordinary Drink,Highball glass,Lemon,Shake all ingredients (except carbonated water...,Juice of 1/2,Juice of,1/2,NaN,NaN,NaN
929,Tequila Sour,Ordinary Drink,Whiskey sour glass,Lemon,"Shake tequila, juice of lemon, and powdered su...",Juice of 1/2,Juice of,1/2,NaN,NaN,NaN
956,Whiskey Sour,Ordinary Drink,Old-fashioned glass,Lemon,"Shake with ice. Strain into chilled glass, gar...",Juice of 1/2,Juice of,1/2,NaN,NaN,NaN
962,Wine Punch,Punch / Party Drink,Collins Glass,Lemon,Combine all of the ingredients and pour over a...,2,2,None,NaN,NaN,NaN
1111,Brandy Cobbler,Ordinary Drink,Old-fashioned glass,Lemon,"In an old-fashioned glass, dissolve the sugar ...",1,1,None,NaN,NaN,NaN
1130,Chicago Fizz,Ordinary Drink,Highball glass,Lemon,Shake all ingredients (except carbonated water...,Juice of 1/2,Juice of,1/2,NaN,NaN,NaN
1137,Clover Club,Ordinary Drink,Cocktail glass,Lemon,"Dry shake ingredients to emulsify, add ice, sh...",Juice of 1/2,Juice of,1/2,NaN,NaN,NaN
1173,Frisco Sour,Ordinary Drink,Whiskey sour glass,Lemon,Shake all ingredients (except slices of lemon ...,Juice of 1/4,Juice of,1/4,NaN,NaN,NaN
1185,Gin Rickey,Cocktail,Highball glass,Lemon,Half-fill a tall glass with ice. Mix the gin a...,Juice of 1/2,Juice of,1/2,NaN,NaN,NaN
1214,Imperial Fizz,Ordinary Drink,Highball glass,Lemon,Shake all ingredients (except carbonated water...,Juice of 1/2,Juice of,1/2,NaN,NaN,NaN
1238,Lemon Drop,Cocktail,Cocktail glass,Lemon,Shake and strain into a chilled cocktail glass...,Juice of 1 wedge,Juice of 1,wedge,NaN,NaN,NaN
1239,Lemon Shot,Shot,Shot glass,Lemon,Mix Galliano and Absolut Citron in a shot glas...,wedge,wedge,None,NaN,NaN,NaN
1292,Quaker's Cocktail,Ordinary Drink,Cocktail glass,Lemon,"Shake all ingredients with ice, strain into a ...",Juice of 1/4,Juice of,1/4,NaN,NaN,NaN
1307,Rum Cobbler,Ordinary Drink,Old-fashioned glass,Lemon,"In an old-fashioned glass, dissolve the sugar ...",1,1,None,NaN,NaN,NaN
1308,Rum Cooler,Ordinary Drink,Collins glass,Lemon,Pour the rum and soda into a collins glass alm...,1,1,None,NaN,NaN,NaN
1320,Sangria - The World's Best,Punch / Party Drink,Pitcher,Lemon,"Mix wine, sugar and fruit, and let sit in the ...",1 large,1,large,NaN,NaN,NaN
1335,Sidecar Cocktail,Ordinary Drink,Cocktail glass,Lemon,"Shake all ingredients with ice, strain into a ...",Juice of 1/4,Juice of,1/4,NaN,NaN,NaN
1340,Snowball,Ordinary Drink,Highball glass,Lemon,Place one ice cube in the glass and add 1 1/2 ...,1 slice,1,slice,NaN,NaN,NaN
1369,Vesuvio,Ordinary Drink,Old-fashioned glass,Lemon,"Shake all ingredients with ice, strain into an...",Juice of 1/2,Juice of,1/2,NaN,NaN,NaN
1479,Brandy Sour,Ordinary Drink,Whiskey sour glass,Lemon,"Shake brandy, juice of lemon, and powdered sug...",1/2 slice,1/2,slice,NaN,NaN,NaN
1501,Dirty Martini,Cocktail,Cocktail glass,Lemon,"Pour the vodka, dry vermouth and olive brine i...",1 wedge,1,wedge,NaN,NaN,NaN
1558,Lady Love Fizz,Ordinary Drink,Cocktail glass,Lemon,Shake all ingredients (except carbonated water...,Juice of 1/2,Juice of,1/2,NaN,NaN,NaN
1571,Mississippi Planters Punch,Ordinary Drink,Collins glass,Lemon,Shake all ingredients (except carbonated water...,Juice of 1/2,Juice of,1/2,NaN,NaN,NaN
1613,Scotch Sour,Ordinary Drink,Whiskey sour glass,Lemon,"Shake scotch, juice of lime, and powdered suga...",1/2 slice,1/2,slice,NaN,NaN,NaN
1616,Shanghai Cocktail,Ordinary Drink,Cocktail glass,Lemon,"Shake all ingredients with ice, strain into a ...",Juice of 1/4,Juice of,1/4,NaN,NaN,NaN
1625,Sunny Holiday Punch,Punch / Party Drink,Punch bowl,Lemon,Combine all ingredients in a punch bowl.,1,1,None,NaN,NaN,NaN
1630,Tequila Sour,Ordinary Drink,Whiskey sour glass,Lemon,"Shake tequila, juice of lemon, and powdered su...",1/2 slice,1/2,slice,NaN,NaN,NaN
1645,Zizi Coin-coin,Punch / Party Drink,Margarita/Coupette glass,Lemon,"Pour 5cl of Cointreau on ice, add 2cl of fresh...",or lime,or,lime,NaN,NaN,NaN
1655,Absolut Summertime,Cocktail,Collins glass,Lemon,Add all ingredients except lemon to shaker fil...,1 slice,1,slice,NaN,NaN,NaN
1685,Boston Sour,Ordinary Drink,Whiskey sour glass,Lemon,"Shake juice of lemon, powdered sugar, blended ...",1 slice,1,slice,NaN,NaN,NaN
1714,Frisco Sour,Ordinary Drink,Whiskey sour glass,Lemon,Shake all ingredients (except slices of lemon ...,1 slice,1,slice,NaN,NaN,NaN
1740,Long Island Tea,Ordinary Drink,Highball glass,Lemon,Combine all ingredients (except cola) and pour...,Juice of 1/2,Juice of,1/2,NaN,NaN,NaN
1752,New York Sour,Ordinary Drink,Whiskey sour glass,Lemon,"Shake blended whiskey, juice of lemon, and pow...",,None,None,NaN,NaN,NaN
1791,Whiskey Sour,Ordinary Drink,Old-fashioned glass,Lemon,"Shake with ice. Strain into chilled glass, gar...",1/2 slice,1/2,slice,NaN,NaN,NaN
1809,Bloody Maria,Ordinary Drink,Old-fashioned glass,Lemon,Shake all ingredients (except lemon slice) wit...,1 slice,1,slice,NaN,NaN,NaN
1885,Sweet Sangria,Punch / Party Drink,Pitcher,Lemon,Dissolve the sugar in hot water and cool. Peel...,,None,None,NaN,NaN,NaN
1886,Zoksel,Soft Drink / Soda,Beer pilsner,Lemon,"No specific mixinginstructions, just poor ever...",,None,None,NaN,NaN,NaN
1901,3-Mile Long Island Iced Tea,Ordinary Drink,Collins Glass,Lemon,Fill 14oz glass with ice and alcohol. Fill 2/3...,,None,None,NaN,NaN,NaN

In [30]:
cond1 = df_cons['strIngredients'] == 'Lemon'
cond2 = df_cons['Value'] == 'Juice of'
cond3 = df_cons['MeasureName'] == '1'
cond4 = df_cons['MeasureName'] == '1/2'
cond5 = df_cons['MeasureName'] == '1/4'

df_cons['Value_ml'] = np.where(cond1 & cond2 & cond3, 45, df_cons['Value_ml'])  #45 is aprox amount of ml of juice in 1 lemon
df_cons['Value_ml'] = np.where(cond1 & cond2 & cond4, 45/2, df_cons['Value_ml'])
df_cons['Value_ml'] = np.where(cond1 & cond2 & cond5, 45/4, df_cons['Value_ml'])

In [33]:
df_cons.loc[(df_cons['strIngredients'] == 'Lemon') & df_cons['Value_ml'].isnull()]

,strDrink,strCategory,strGlass,strIngredients,strInstructions,strMeasures,Value,MeasureName,Value_ml,Garnish_amount,Garnish_type
1238,Lemon Drop,Cocktail,Cocktail glass,Lemon,Shake and strain into a chilled cocktail glass...,Juice of 1 wedge,Juice of 1,wedge,NaN,NaN,NaN
1239,Lemon Shot,Shot,Shot glass,Lemon,Mix Galliano and Absolut Citron in a shot glas...,wedge,wedge,None,NaN,NaN,NaN
1340,Snowball,Ordinary Drink,Highball glass,Lemon,Place one ice cube in the glass and add 1 1/2 ...,1 slice,1,slice,NaN,NaN,NaN
1479,Brandy Sour,Ordinary Drink,Whiskey sour glass,Lemon,"Shake brandy, juice of lemon, and powdered sug...",1/2 slice,1/2,slice,NaN,NaN,NaN
1501,Dirty Martini,Cocktail,Cocktail glass,Lemon,"Pour the vodka, dry vermouth and olive brine i...",1 wedge,1,wedge,NaN,NaN,NaN
1613,Scotch Sour,Ordinary Drink,Whiskey sour glass,Lemon,"Shake scotch, juice of lime, and powdered suga...",1/2 slice,1/2,slice,NaN,NaN,NaN
1630,Tequila Sour,Ordinary Drink,Whiskey sour glass,Lemon,"Shake tequila, juice of lemon, and powdered su...",1/2 slice,1/2,slice,NaN,NaN,NaN
1655,Absolut Summertime,Cocktail,Collins glass,Lemon,Add all ingredients except lemon to shaker fil...,1 slice,1,slice,NaN,NaN,NaN
1685,Boston Sour,Ordinary Drink,Whiskey sour glass,Lemon,"Shake juice of lemon, powdered sugar, blended ...",1 slice,1,slice,NaN,NaN,NaN
1714,Frisco Sour,Ordinary Drink,Whiskey sour glass,Lemon,Shake all ingredients (except slices of lemon ...,1 slice,1,slice,NaN,NaN,NaN
1752,New York Sour,Ordinary Drink,Whiskey sour glass,Lemon,"Shake blended whiskey, juice of lemon, and pow...",,None,None,NaN,NaN,NaN
1791,Whiskey Sour,Ordinary Drink,Old-fashioned glass,Lemon,"Shake with ice. Strain into chilled glass, gar...",1/2 slice,1/2,slice,NaN,NaN,NaN
1809,Bloody Maria,Ordinary Drink,Old-fashioned glass,Lemon,Shake all ingredients (except lemon slice) wit...,1 slice,1,slice,NaN,NaN,NaN
1885,Sweet Sangria,Punch / Party Drink,Pitcher,Lemon,Dissolve the sugar in hot water and cool. Peel...,,None,None,NaN,NaN,NaN
1886,Zoksel,Soft Drink / Soda,Beer pilsner,Lemon,"No specific mixinginstructions, just poor ever...",,None,None,NaN,NaN,NaN
1901,3-Mile Long Island Iced Tea,Ordinary Drink,Collins Glass,Lemon,Fill 14oz glass with ice and alcohol. Fill 2/3...,,None,None,NaN,NaN,NaN

In [32]:
cond1 = df_cons['strIngredients'] == 'Lemon'
cond2 = df_cons['MeasureName'].isnull()
cond3 = df_cons['MeasureName'] == 'large'
cond4 = df_cons['Value'] == '1'
cond5 = df_cons['Value'] == '2'
cond6 = df_cons['Value'] == '1/2'
cond7 = df_cons['MeasureName'] == 'lime'

df_cons['Value_ml'] = np.where(cond1 & (cond2 | cond3) & cond4, 45, df_cons['Value_ml'])
df_cons['Value_ml'] = np.where(cond1 & (cond2 | cond3) & cond5, 45*2, df_cons['Value_ml'])
df_cons['Value_ml'] = np.where(cond1 & (cond2 | cond3) & cond6, 45/2, df_cons['Value_ml'])
df_cons['Value_ml'] = np.where(cond1 & cond7, 20, df_cons['Value_ml'])  # Recipe verified via Internet manually

In [34]:
df_cons.loc[(df_cons['strIngredients'] == 'Lemon') & df_cons['Value_ml'].isnull()]

,strDrink,strCategory,strGlass,strIngredients,strInstructions,strMeasures,Value,MeasureName,Value_ml,Garnish_amount,Garnish_type
1238,Lemon Drop,Cocktail,Cocktail glass,Lemon,Shake and strain into a chilled cocktail glass...,Juice of 1 wedge,Juice of 1,wedge,NaN,NaN,NaN
1239,Lemon Shot,Shot,Shot glass,Lemon,Mix Galliano and Absolut Citron in a shot glas...,wedge,wedge,None,NaN,NaN,NaN
1340,Snowball,Ordinary Drink,Highball glass,Lemon,Place one ice cube in the glass and add 1 1/2 ...,1 slice,1,slice,NaN,NaN,NaN
1479,Brandy Sour,Ordinary Drink,Whiskey sour glass,Lemon,"Shake brandy, juice of lemon, and powdered sug...",1/2 slice,1/2,slice,NaN,NaN,NaN
1501,Dirty Martini,Cocktail,Cocktail glass,Lemon,"Pour the vodka, dry vermouth and olive brine i...",1 wedge,1,wedge,NaN,NaN,NaN
1613,Scotch Sour,Ordinary Drink,Whiskey sour glass,Lemon,"Shake scotch, juice of lime, and powdered suga...",1/2 slice,1/2,slice,NaN,NaN,NaN
1630,Tequila Sour,Ordinary Drink,Whiskey sour glass,Lemon,"Shake tequila, juice of lemon, and powdered su...",1/2 slice,1/2,slice,NaN,NaN,NaN
1655,Absolut Summertime,Cocktail,Collins glass,Lemon,Add all ingredients except lemon to shaker fil...,1 slice,1,slice,NaN,NaN,NaN
1685,Boston Sour,Ordinary Drink,Whiskey sour glass,Lemon,"Shake juice of lemon, powdered sugar, blended ...",1 slice,1,slice,NaN,NaN,NaN
1714,Frisco Sour,Ordinary Drink,Whiskey sour glass,Lemon,Shake all ingredients (except slices of lemon ...,1 slice,1,slice,NaN,NaN,NaN
1752,New York Sour,Ordinary Drink,Whiskey sour glass,Lemon,"Shake blended whiskey, juice of lemon, and pow...",,None,None,NaN,NaN,NaN
1791,Whiskey Sour,Ordinary Drink,Old-fashioned glass,Lemon,"Shake with ice. Strain into chilled glass, gar...",1/2 slice,1/2,slice,NaN,NaN,NaN
1809,Bloody Maria,Ordinary Drink,Old-fashioned glass,Lemon,Shake all ingredients (except lemon slice) wit...,1 slice,1,slice,NaN,NaN,NaN
1885,Sweet Sangria,Punch / Party Drink,Pitcher,Lemon,Dissolve the sugar in hot water and cool. Peel...,,None,None,NaN,NaN,NaN
1886,Zoksel,Soft Drink / Soda,Beer pilsner,Lemon,"No specific mixinginstructions, just poor ever...",,None,None,NaN,NaN,NaN
1901,3-Mile Long Island Iced Tea,Ordinary Drink,Collins Glass,Lemon,Fill 14oz glass with ice and alcohol. Fill 2/3...,,None,None,NaN,NaN,NaN

In [39]:
df_cons.loc[df_cons['MeasureName'] == 'wedge']

,strDrink,strCategory,strGlass,strIngredients,strInstructions,strMeasures,Value,MeasureName,Value_ml,Garnish_amount,Garnish_type
1238,Lemon Drop,Cocktail,Cocktail glass,Lemon,Shake and strain into a chilled cocktail glass...,Juice of 1 wedge,Juice of 1,wedge,22.5,NaN,NaN
1501,Dirty Martini,Cocktail,Cocktail glass,Lemon,"Pour the vodka, dry vermouth and olive brine i...",1 wedge,1,wedge,NaN,1,wedge
1810,Bloody Mary,Ordinary Drink,Old-fashioned glass,Lime,"Stirring gently, pour all ingredients into hig...",1 wedge,1,wedge,NaN,1,wedge
1889,3-Mile Long Island Iced Tea,Ordinary Drink,Collins Glass,Bitters,Fill 14oz glass with ice and alcohol. Fill 2/3...,1 wedge,1,wedge,NaN,NaN,NaN
1904,Arizona Twister,Cocktail,Hurricane glass,Pineapple,"Just mix in the shots of rum, vodka, and tequi...",1 wedge,1,wedge,NaN,1,wedge

In [ ]:
df_cons.loc[df_cons['MeasureName'] == 'slice']

In [36]:
cond1 = df_cons['strIngredients'] == 'Lemon'
cond2 = df_cons['strDrink'] == 'Lemon Drop'
df_cons['Value_ml'] = np.where(cond1 & cond2, 45/2, df_cons['Value_ml']) # Although it says juice of 1 wedge, most common recipe
                                                                        # is to use juice of 1/2 of lemon.

In [38]:
cond1 = df_cons['MeasureName'].isin(['slice', 'wedge'])
cond2 = ~df_cons['strDrink'].isin(['Lemon Drop', '3-Mile Long Island Iced Tea'])

df_cons['Garnish_type'] = np.where(cond1 & cond2, df_cons['MeasureName'], df_cons['Garnish_type'])
df_cons['Garnish_amount'] = np.where(cond1 & cond2, df_cons['Value'], df_cons['Garnish_amount'])

In [58]:
df_cons.loc[(df_cons['strIngredients'] == 'Lemon') & (df_cons['Value_ml'].isnull()) & df_cons['Garnish_type'].isnull()]

Empty DataFrame
Columns: [strDrink, strCategory, strGlass, strIngredients, strInstructions, strMeasures, Value, MeasureName, Value_ml, Garnish_amount, Garnish_type]
Index: []

In [41]:
cond1 = df_cons['strIngredients'] == 'Lemon'
cond2 = df_cons['strDrink'] == 'Lemon Shot'
df_cons['Garnish_amount'] = np.where(cond1 & cond2, 1, df_cons['Garnish_amount'])
df_cons['Garnish_type'] = np.where(cond1 & cond2, 'wedge', df_cons['Garnish_type'])

In [42]:
cond1 = df_cons['strIngredients'] == 'Lemon'
cond2 = df_cons['strDrink'] == 'New York Sour'
df_cons['Garnish_amount'] = np.where(cond1 & cond2, '1/2', df_cons['Garnish_amount'])
df_cons['Garnish_type'] = np.where(cond1 & cond2, 'slice', df_cons['Garnish_type'])

Check remaining cocktails one by one.

In [44]:
recipe('Sweet Sangria')

Dissolve the sugar in hot water and cool. Peel the citrus fruits and break into wedges. Mix the wine, sugar syrup, fruit, and Fresca in a pitcher and put in the fridge for a few hours. Serve in tall glasses with a straw.

   Ingredient      Measure
0    Red wine   2 bottles
1       Sugar       1 cup
2       Water  2 cups hot
3       Apple       1 cup
4      Orange     wedges\n
5        Lime     wedges\n
6       Lemon          NaN
7      Fresca          NaN
8         NaN          NaN
9         NaN          NaN
10        NaN          NaN
11        NaN          NaN

In [45]:
# Should be dropped as measures are too messy and it's impossible to recover original recipe.
df_cons.drop(df_cons.loc[df_cons['strDrink'] == 'Sweet Sangria'].index, axis=0, inplace=True)

In [46]:
recipe('Zoksel')

No specific mixinginstructions, just poor every ingredient in one glass. The lemon goes with it.

         Ingredient   Measure
0              Beer       NaN
1         Root beer       NaN
2          Lemonade       NaN
3         Coca-Cola   slice\n
4              7-Up       NaN
5   Creme de Cassis       NaN
6             Lemon       NaN
7               NaN       NaN
8               NaN       NaN
9               NaN       NaN
10              NaN       NaN
11              NaN       NaN

In [47]:
# This cocktail should be dropped due to lack of guidance.

df_cons.drop(df_cons.loc[df_cons['strDrink'] == 'Zoksel'].index, axis=0, inplace=True)

In [48]:
recipe('3-Mile Long Island Iced Tea')

Fill 14oz glass with ice and alcohol. Fill 2/3 glass with cola and remainder with sweet & sour. Top with dash of bitters and lemon wedge.

        Ingredient    Measure
0              Gin    1/2 oz
1        Light rum    1/2 oz
2          Tequila    1/2 oz
3       Triple sec    1/2 oz
4            Vodka    1/2 oz
5        Coca-Cola        NaN
6   Sweet and sour  1-2 dash
7          Bitters   1 wedge
8            Lemon        NaN
9              NaN        NaN
10             NaN        NaN
11             NaN        NaN

In [56]:
# Measures of this cocktail shifted, also some measures are missing.

cond1 = df_cons['strDrink'] == '3-Mile Long Island Iced Tea'

df_cons['Value_ml'] = np.where(cond1 & (df_cons['strIngredients'] == 'Coca-Cola'), 200, df_cons['Value_ml'])
df_cons['Value_ml'] = np.where(cond1 & (df_cons['strIngredients'] == 'Sweet And Sour'), 30, df_cons['Value_ml'])
df_cons['Value_ml'] = np.where(cond1 & (df_cons['strIngredients'] == 'Bitters'), 1, df_cons['Value_ml'])
df_cons['Garnish_amount'] = np.where(cond1 & (df_cons['strIngredients'] == 'Lemon'), 1, df_cons['Garnish_amount'])
df_cons['Garnish_type'] = np.where(cond1 & (df_cons['strIngredients'] == 'Lemon'), 'wedge', df_cons['Garnish_type'])

In [62]:
df_cons.loc[(df_cons['strIngredients'] == 'Lemon') & (df_cons['Value_ml'].isnull()) & df_cons['Garnish_type'].isnull()]
# We're done with lemon and can move on.

Empty DataFrame
Columns: [strDrink, strCategory, strGlass, strIngredients, strInstructions, strMeasures, Value, MeasureName, Value_ml, Garnish_amount, Garnish_type]
Index: []

## Limes.

In [81]:
df_cons.loc[(df_cons['strIngredients'] == 'Lime') & (df_cons['Value_ml'].isnull()) & df_cons['Garnish_type'].isnull()]

,strDrink,strCategory,strGlass,strIngredients,strInstructions,strMeasures,Value,MeasureName,Value_ml,Garnish_amount,Garnish_type
684,Cuba Libra,Ordinary Drink,Highball glass,Lime,Fill tall glass with ice cubes. Add rum. Rub c...,Squeeze,Squeeze,None,NaN,NaN,NaN
1203,Happy Skipper,Ordinary Drink,Highball glass,Lime,"Pour Captain Morgan's Spiced Rum over ice, fil...",,None,None,NaN,NaN,NaN
1719,Gin Rickey,Cocktail,Highball glass,Lime,Half-fill a tall glass with ice. Mix the gin a...,Garnish,Garnish,None,NaN,NaN,NaN

In [80]:
cond1 = (df_cons['strIngredients'] == 'Lime') & (df_cons['Value_ml'].isnull()) & df_cons['Garnish_type'].isnull()
cond2 = (df_cons['Value'] == '1/2')|(df_cons['MeasureName'] == '1/2')
cond3 = (df_cons['Value'] == '1')|(df_cons['MeasureName'] == '1')
cond4 = (df_cons['Value'] == '2')

df_cons['Value_ml'] = np.where(cond1 & cond2, 30/2, df_cons['Value_ml'])
df_cons['Value_ml'] = np.where(cond1 & cond3, 30, df_cons['Value_ml'])
df_cons['Value_ml'] = np.where(cond1 & cond4, 30*2, df_cons['Value_ml'])

In [82]:
df_cons.loc[(df_cons['strIngredients'] == 'Lime') & (df_cons['Value_ml'].isnull()) & df_cons['Garnish_type'].isnull()]

,strDrink,strCategory,strGlass,strIngredients,strInstructions,strMeasures,Value,MeasureName,Value_ml,Garnish_amount,Garnish_type
684,Cuba Libra,Ordinary Drink,Highball glass,Lime,Fill tall glass with ice cubes. Add rum. Rub c...,Squeeze,Squeeze,None,NaN,NaN,NaN
1203,Happy Skipper,Ordinary Drink,Highball glass,Lime,"Pour Captain Morgan's Spiced Rum over ice, fil...",,None,None,NaN,NaN,NaN
1719,Gin Rickey,Cocktail,Highball glass,Lime,Half-fill a tall glass with ice. Mix the gin a...,Garnish,Garnish,None,NaN,NaN,NaN

Again, let's check remaining cocktails one by one.

In [83]:
recipe('Cuba Libra')

Fill tall glass with ice cubes. Add rum. Rub cut edge of lime on rim of glass then squeeze juice into glass. Fill with Coca-Cola. Garnish with lime slice. Enjoy!

   Ingredient     Measure
0    Dark rum   1-2 shot
1        Lime    Squeeze
2   Coca-Cola  Fill with
3         Ice         NaN
4         NaN         NaN
5         NaN         NaN
6         NaN         NaN
7         NaN         NaN
8         NaN         NaN
9         NaN         NaN
10        NaN         NaN
11        NaN         NaN

In [84]:
cond1 = (df_cons['strIngredients'] == 'Lime') & (df_cons['Value_ml'].isnull()) & df_cons['Garnish_type'].isnull()
cond2 = df_cons['strDrink'] == 'Cuba Libra'

df_cons['Value_ml'] = np.where(cond1 & cond2, 30, df_cons['Value_ml'])

In [85]:
recipe('Happy Skipper')

Pour Captain Morgan's Spiced Rum over ice, fill glass to top with Ginger Ale. Garnish with lime. Tastes like a cream soda. Named for the Gilligan's Island reference ("The Captain" *in* "Ginger" is a Happy Skipper!)

    Ingredient    Measure
0   Spiced rum  1 1/2 cl
1   Ginger ale        NaN
2         Lime        NaN
3          Ice        NaN
4          NaN        NaN
5          NaN        NaN
6          NaN        NaN
7          NaN        NaN
8          NaN        NaN
9          NaN        NaN
10         NaN        NaN
11         NaN        NaN

In [86]:
recipe('Gin Rickey')

Half-fill a tall glass with ice. Mix the gin and Grenadine together and pour over the ice. Add the lime or lemon juice and top off with soda water. Decorate the glass with lime and/or lemon slices.

    Ingredient        Measure
0          Gin          2 oz
1    Grenadine         1 tsp
2        lemon  Juice of 1/2
3   Soda Water    Top up with
4         Lime        Garnish
5          NaN            NaN
6          NaN            NaN
7          NaN            NaN
8          NaN            NaN
9          NaN            NaN
10         NaN            NaN
11         NaN            NaN

In [87]:
cond1 = (df_cons['strIngredients'] == 'Lime') & (df_cons['Value_ml'].isnull()) & df_cons['Garnish_type'].isnull()
cond2 = df_cons['strDrink'].isin(['Happy Skipper', 'Gin Rickey'])

df_cons['Garnish_amount'] = np.where(cond1 & cond2, 1, df_cons['Garnish_amount'])
df_cons['Garnish_type'] = np.where(cond1 & cond2, 'slice', df_cons['Garnish_type'])

In [88]:
df_cons.loc[(df_cons['strIngredients'] == 'Lime') & (df_cons['Value_ml'].isnull()) & df_cons['Garnish_type'].isnull()]

Empty DataFrame
Columns: [strDrink, strCategory, strGlass, strIngredients, strInstructions, strMeasures, Value, MeasureName, Value_ml, Garnish_amount, Garnish_type]
Index: []

## Oranges.

In [114]:
df_cons.loc[(df_cons['strIngredients'] == 'Orange') & (df_cons['Value_ml'].isnull()) & df_cons['Garnish_type'].isnull()]

,strDrink,strCategory,strGlass,strIngredients,strInstructions,strMeasures,Value,MeasureName,Value_ml,Garnish_amount,Garnish_type
1472,Bourbon Sour,Ordinary Drink,Whiskey sour glass,Orange,"In a shaker half-filled with ice cubes, combin...",1,1,None,NaN,NaN,NaN
1528,Gin Sour,Ordinary Drink,Whiskey sour glass,Orange,"In a shaker half-filled with ice cubes, combin...",1,1,None,NaN,NaN,NaN
1605,Rum Sour,Ordinary Drink,Whiskey sour glass,Orange,"In a shaker half-filled with ice cubes, combin...",1,1,None,NaN,NaN,NaN
1643,Wine Punch,Punch / Party Drink,Collins Glass,Orange,Combine all of the ingredients and pour over a...,3,3,None,NaN,NaN,NaN
1700,Classic Old-Fashioned,Ordinary Drink,Old-fashioned glass,Orange,"In an old-fashioned glass, muddle the bitters ...",1,1,None,NaN,NaN,NaN
1713,French 75,Ordinary Drink,Collins glass,Orange,"Combine gin, sugar, and lemon juice in a cockt...",1,1,None,NaN,NaN,NaN
1804,Apricot Lady,Ordinary Drink,Old-fashioned glass,Orange,"In a shaker half-filled with ice cubes, combin...",1,1,None,NaN,NaN,NaN
1815,Brandy Cobbler,Ordinary Drink,Old-fashioned glass,Orange,"In an old-fashioned glass, dissolve the sugar ...",1,1,None,NaN,NaN,NaN
1831,Gin Daisy,Ordinary Drink,Old-fashioned glass,Orange,"In a shaker half-filled with ice cubes, combin...",1,1,None,NaN,NaN,NaN
1839,John Collins,Ordinary Drink,Collins glass,Orange,Pour all ingredients directly into highball gl...,1,1,None,NaN,NaN,NaN
1851,Rum Cobbler,Ordinary Drink,Old-fashioned glass,Orange,"In an old-fashioned glass, dissolve the sugar ...",1,1,None,NaN,NaN,NaN
1861,Tom Collins,Ordinary Drink,Collins glass,Orange,"In a shaker half-filled with ice cubes, combin...",1,1,None,NaN,NaN,NaN

In [113]:
cond1 = (df_cons['strDrink'] == 'Abbey Cocktail')
cond2 = (df_cons['strIngredients'] == 'Orange')
df_cons['Value_ml'] = np.where(cond1 & cond2, 75/4, df_cons['Value_ml'])

In [109]:
recipe('John Collins')

Pour all ingredients directly into highball glass filled with ice. Stir gently. Garnish. Add a dash of Angostura bitters.

           Ingredient           Measure
0             Bourbon             2 oz
1         Lemon juice             1 oz
2               Sugar  1 tsp superfine
3           Club soda             3 oz
4   Maraschino cherry                1
5              Orange                1
6                 NaN               NaN
7                 NaN               NaN
8                 NaN               NaN
9                 NaN               NaN
10                NaN               NaN
11                NaN               NaN

In [91]:
recipe('Caribbean Orange Liqueur')

Pare very thinly the bright-colored rind from the oranges (no white). Blot the peel on paper towels to remove any excess oil. Put peel in a 4 cup screw-top jar. Add 2 cups vodka. Close jar. Store in a cool, dark place for 2 days or until the vodka has absorbed the flavor. Remove peel and add remaining vodka. Close jar and add remaining cup of vodka. Close the jar and store in a cool dark place at least 1 month to age.

   Ingredient               Measure
0      Orange              3 large
1       Vodka               3 cups
2       Sugar  1 1/3 cup superfine
3         NaN                   NaN
4         NaN                   NaN
5         NaN                   NaN
6         NaN                   NaN
7         NaN                   NaN
8         NaN                   NaN
9         NaN                   NaN
10        NaN                   NaN
11        NaN                   NaN

In [126]:
# It's actually not a cocktail and should be dropped together with all other homemage liqueurs.
df_cons.drop(df_cons.loc[df_cons['strCategory']=='Homemade Liqueur'].index, axis=0, inplace=True)

In [102]:
recipe("Sangria - The World's Best")

Mix wine, sugar and fruit, and let sit in the fridge for 18-24 hours. The mixture will have a somewhat syrupy consistency. Before serving stir in brandy and cut the mixture with soda water until it have a thinner, more wine like consistency. Serve from a pitcher in wine glasses.

    Ingredient        Measure
0     Red wine       1 1/2 L
1        Sugar         1 cup
2        Lemon       1 large
3       Orange       1 large
4        Apple       1 large
5       Brandy  3-4 oz plain
6   Soda water            NaN
7          NaN            NaN
8          NaN            NaN
9          NaN            NaN
10         NaN            NaN
11         NaN            NaN

In [103]:
recipe('Wine Punch')

Combine all of the ingredients and pour over a block of ice.

         Ingredient    Measure
0          Red wine  1 bottle
1             Lemon         2
2      Orange juice     1 cup
3            Orange         3
4   Pineapple juice     1 cup
5               NaN        NaN
6               NaN        NaN
7               NaN        NaN
8               NaN        NaN
9               NaN        NaN
10              NaN        NaN
11              NaN        NaN

In [112]:
# For Sangria amount of oranges specified stays for juice but for the rest it's for garnish by slices.
cond1 = (df_cons['strDrink'] == "Sangria - The World's Best")
cond2 = (df_cons['strIngredients'] == 'Orange')
df_cons['Value_ml'] = np.where(cond1 & cond2, 75*3, df_cons['Value_ml'])

In [107]:
# Cocktail 'French "75"' appeares two times.

df_cons.drop(df_cons.loc[df_cons['strDrink']=='French "75"'].index, axis=0, inplace=True)

In [115]:
# Add orange slice as a garnish for remaining cocktails.

cond1 = (df_cons['strIngredients'] == 'Orange') & (df_cons['Value_ml'].isnull()) & df_cons['Garnish_type'].isnull()

df_cons['Garnish_amount'] = np.where(cond1, df_cons['Value'], df_cons['Garnish_amount'])
df_cons['Garnish_type'] = np.where(cond1, 'slice', df_cons['Garnish_type'])

In [118]:
df_cons.loc[(df_cons['strIngredients'] == 'Orange') & (df_cons['Value_ml'].isnull()) & df_cons['Garnish_type'].isnull()]

Empty DataFrame
Columns: [strDrink, strCategory, strGlass, strIngredients, strInstructions, strMeasures, Value, MeasureName, Value_ml, Garnish_amount, Garnish_type]
Index: []

## Apples.

In [119]:
df_cons.loc[(df_cons['strIngredients'] == 'Apple') & (df_cons['Value_ml'].isnull()) & df_cons['Garnish_type'].isnull()]

,strDrink,strCategory,strGlass,strIngredients,strInstructions,strMeasures,Value,MeasureName,Value_ml,Garnish_amount,Garnish_type
1767,Sangria - The World's Best,Punch / Party Drink,Pitcher,Apple,"Mix wine, sugar and fruit, and let sit in the ...",1 large,1,large,NaN,NaN,NaN

In [120]:
cond1 = (df_cons['strDrink'] == "Sangria - The World's Best")
cond2 = (df_cons['strIngredients'] == 'Apple')
df_cons['Value_ml'] = np.where(cond1 & cond2, 100, df_cons['Value_ml'])

## Converting standard measures to ml.

In [190]:
# Set up intermediary column for values defined as float.
df_cons['Value_numeric'] = np.nan

Values will be converted to numberic in batches related to other characteristics, this way it's easier to process the mess and avoid mistakes.

In [136]:
df_cons.loc[(df_cons['Value_ml'].isnull()) & df_cons['Garnish_type'].isnull()]['MeasureName'].unique()

array(['white', 'oz', 'shot', 'bacardi', None, 'dry', 'part', 'jigger',
       'shots', 'cl', 'dashes', 'scoops', 'hot', 'qt', 'parts', 'blue',
       'ml', 'tsp', 'black', 'smirnoff', 'can', 'cubes', 'pint', 'pale',
       'cups', 'superfine', 'fifth', 'bottle', 'cup', 'glass', 'l',
       'hard', 'strip', 'jiggers', 'light', 'grape', 'handful', 'tblsp',
       '1/2', 'dark', 'jamaican', 'cream', 'chilled', 'measures', 'or',
       'stoli', 'splash', 'dash', 'red', 'ginger', 'lemon', 'quart',
       'hill', 'label', 'whole', 'piece', 'tbsp', 'chunks', 'sweet',
       'cold', 'packages', 'tropical', 'apple', 'blended', 'cans',
       'drops', 'with', 'of', 'frozen', 'gal', 'muscatel', 'leaves',
       'skimmed', 'cube', 'gr', 'taste', 'needed)', 'double', 'sweetened',
       'splashes', 'spoons', 'unsweetened', 'top', 'crushed', 'berry',
       'topping', 'pinches', 'schweppes', '3', 'package', 'grated',
       'fresh', 'up', 'fill', 'tablespoons', 'pinch', 'hazlenut', 'plain',
       'ground', 'sprigs', 'sticks'], dtype=object)

## oz.

In [196]:
# Define oz variable to convert oz to ml.

oz = 30

In [146]:
temp = df_cons.loc[(df_cons['MeasureName'] == 'oz')]
temp['Value'].unique()

array(['1/2', '16', '1/3', '2-3', '2 1/2', '2', '1', '1 1/2', '3/4', '3',
       '5', '6', '1 1/4', '0.75', '70ml/2fl', '2/3', '1 2/3', '1.5', '4',
       '12', '8', '1/4', '0.25', '0.5', '28', 'Add 10', '7', '3-4',
       '10-12'], dtype=object)

In [192]:
values_replace = {'1/2':0.5, '16':16, '1/3':1/3, '2-3':2.5, '2 1/2':2.5, '2':2, '1':1, '1 1/2':1.5, '3/4':3/4, '3':3,
                   '5':5, '6':6, '1 1/4':1.25, '0.75':0.75, '70ml/2fl':70, '2/3':2/3, '1 2/3':(1+2/3), '1.5':1.5, '4':4,
                   '12':12, '8':8, '1/4':1/4, '0.25':0.25, '0.5':0.5, '28':28, 'Add 10':10, '7':7, '3-4':3.5,'10-12':11}

def repl_from_dic(dic, row):
    if row.Value in dic.keys():
        return dic[row.Value]
    else:
        return row.Value_numeric

# repl_from_dic(values_replace, df_cons.iloc[2])
df_cons['Value_numeric'] = df_cons.loc[(df_cons['MeasureName'] == 'oz')].apply(lambda row: repl_from_dic(values_replace, row),
                                                                               axis=1)

In [197]:
df_cons['Value_ml'] = np.where(df_cons['MeasureName'] == 'oz', df_cons['Value_numeric']*oz, df_cons['Value_ml'])

In [198]:
df_cons.loc[(~df_cons['Value_numeric'].isnull())]

,strDrink,strCategory,strGlass,strIngredients,strInstructions,strMeasures,Value,MeasureName,Value_ml,Garnish_amount,Garnish_type,Value_numeric
1,1-900-FUK-MEUP,Shot,Old-fashioned glass,Absolut Kurant,Shake ingredients in a mixing tin filled with ...,1/2 oz,1/2,oz,15.0,NaN,NaN,0.500000
2,110 in the shade,Beer,Beer Glass,Lager,Drop shooter in glass. Fill with beer,16 oz,16,oz,480.0,NaN,NaN,16.000000
3,151 Florida Bushwacker,Milk / Float / Shake,Beer mug,Malibu Rum,Combine all ingredients. Blend until smooth. G...,1/2 oz,1/2,oz,15.0,NaN,NaN,0.500000
5,24k nightmare,Shot,Shot glass,Goldschlager,"Add over ice,shake and pour.",1/2 oz,1/2,oz,15.0,NaN,NaN,0.500000
7,3 Wise Men,Shot,Collins glass,Jack Daniels,put them them in a glass... and slam it to tha...,1/3 oz,1/3,oz,10.0,NaN,NaN,0.333333
...,...,...,...,...,...,...,...,...,...,...,...,...
1876,Cherry Electric Lemonade,Cocktail,Pint glass,Sweet And Sour,Now stir vigorously and then pour over a large...,1 oz,1,oz,30.0,NaN,NaN,1.000000
1883,Radioactive Long Island Iced Tea,Ordinary Drink,Collins Glass,Midori Melon Liqueur,Pour all ingredients over ice in a very tall g...,1 oz,1,oz,30.0,NaN,NaN,1.000000
1887,1-900-FUK-MEUP,Shot,Old-fashioned glass,Pineapple Juice,Shake ingredients in a mixing tin filled with ...,1/4 oz,1/4,oz,7.5,NaN,NaN,0.250000
1896,Cherry Electric Lemonade,Cocktail,Pint glass,Club Soda,Now stir vigorously and then pour over a large...,3 oz,3,oz,90.0,NaN,NaN,3.000000
1899,Radioactive Long Island Iced Tea,Ordinary Drink,Collins Glass,Malibu Rum,Pour all ingredients over ice in a very tall g...,1 oz,1,oz,30.0,NaN,NaN,1.000000

## cl.

In [205]:
# Define cl variable to convert cl to ml.

cl = 10

In [204]:
temp = df_cons.loc[(df_cons['Value_ml'].isnull()) & (df_cons['Garnish_type'].isnull()) & (df_cons['MeasureName'] == 'cl')]
temp['Value'].unique()

array(['2', '1', '4', '4.5', '5', '6', '1 1/2', '2.5', '3', '1.5', '10',
       '8', '16', '1/4', '7', '0.75'], dtype=object)

In [ ]:
# Check if there are values in both ml and garnish.

In [138]:
temp = df_cons.loc[(df_cons['Value_ml'].isnull()) & (df_cons['Garnish_type'].isnull()) & (df_cons['MeasureName'] == 'oz')]
temp['Value'].unique()

array(['1/2', '16', '1/3', '2-3', '2 1/2', '2', '1', '1 1/2', '3/4', '3',
       '5', '6', '1 1/4', '0.75', '70ml/2fl', '2/3', '1 2/3', '1.5', '4',
       '12', '8', '1/4', '0.25', '0.5', '28', 'Add 10', '7', '3-4',
       '10-12'], dtype=object)